name: test-actions
on: 
  push: 
    branches:
      - main
      - develop
  pull_request:
    branches:
    - main
    - develop
jobs:
  test:
    name: MarvelFeed Test
    runs-on: macOS-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
      - name: Force XCode 12.3
        run: sudo xcode-select -switch /Applications/Xcode_12.3.app
      - name: Testing iOS app
        run: xcodebuild test -project MarvelFeed.xcodeproj -scheme MarvelFeedTests -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 12,OS=14.3"

